connector-slack:
    hostname: connector-slack
    build: ./connector-slack
    volumes:
        - ../gary-connector/slack:/bot
        - ./logs/connector-slack:/var/log/connector-slack
    environment:
        - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
        - SLACK_BOT_ID=${SLACK_BOT_ID}
    tty: true
connector-messenger:
    hostname: connector-messenger
    build: ./connector-messenger
    volumes:
        - ../gary-connector/messenger:/bot
        - ./logs/connector-messenger:/var/log/connector-messenger
    environment:
        - MESSENGER_BOT_TOKEN=${MESSENGER_BOT_TOKEN}
        - MESSENGER_BOT_ID=${MESSENGER_BOT_ID}
    tty: true
nlp:
    hostname: nlp
    build: ./nlp
    links:
        - "mongo"
    volumes:
        - ../gary-nlp:/bot
        - ./logs/nlp:/var/log/nlp
    tty: true
mongo:
    hostname: mongo
        - "connector-slack"
        - "connector-messenger"
    build: ./mongo
    environment:
        - DB_PASS=${DB_PASS}
        - DB_USER=${DB_USER}
    ports:
        - 27017:27017
    tty: true
